### PR TITLE
[75] fix tournament list response being empty octet stream; docs, indentation

### LINKED ISSUE #75: Empty tournament list response is an empty octet stream; documentation doesn't match up
This is a fragment of the current get_tournaments code; not only is the `if visible_tournaments.is_empty()` redundant, as the vec will already be empty and sent as a reponse, it breaks the code - while implicit return on the last line converts the resulting computed vector (which can still be empty!) into Json, the inner one doesn't.

A vec![] converted into a response is not a JSON object. It's an empty Vector, it has no data, so it's converted into nothing; an empty octet stream. No bytes are sent in the response body - and the frontend expects a JSON object in all 200 OK responses, meaning it crashes and burns if deployed on a backend instance where a tournament wasn't created yet.

```rust
let mut visible_tournaments: Vec<Tournament> = vec![];
for tournament in tournaments {
    let tournament_id = tournament.id;
    let roles = user.get_roles(tournament_id, pool).await?;
    let tournament_user = TournamentUser {
        user: user.clone(),
        roles,
    };
    if tournament_user.has_permission(Permission::ReadTournament) {
        visible_tournaments.push(tournament);
    }
}
if visible_tournaments.is_empty() {
    return Ok(vec![].into_response());
}
Ok(Json(visible_tournaments).into_response())
```

The documentation macro also states that a 401 is sent if a user is not permitted to list any tournaments, so in the case just discussed. No such thing happens, not to mention it being kind of a misuse of the code.

### PR DESCRIPTION
**Pull request by jakubmanczak**
Closes #75 by implementing the outlined fixes. Also aligns indentation with whatever rustfmt outputs.

### CODE REVIEW

File: src/routes/tournament_routes.rs [hunk 1]
```diff
@@ -23,22 +27,18 @@ pub fn route() -> Router<AppState> {
...
     responses(
         (
             status=200, description = "Ok",
             body=Vec<Tournament>,
             example=json!(get_tournaments_list_example())
         ),
         (status=400, description = "Bad request"),
-        (
-            status=401, 
-            description = "The user is not permitted to list any tournaments, meaning they do not have any roles within any tournament."
```
Comment (Mateusz-Dobrzynski) [inline src/routes/tournament_routes.rs:40]: 401 is among possible responses served by this endpoint and as such must be documented. It occurs when making a request without logging in (and possibly in some other cases that I don't remember at the moment). This description is obviously wrong (must've been copy-pasted from some other endpoint relating to a single tournament), but the solution here is to correct it, not delete altogether.

**Review by Mateusz-Dobrzynski — CHANGES_REQUESTED** [review]
Tested the code, indeed returns an empty JSON now. Documentation, however, was wrongly modified.

**Review by Mateusz-Dobrzynski — APPROVED** [review]
